version: '3.8'

services:
  # Neo4j Graph Database
  neo4j:
    image: neo4j:5.15.0
    container_name: multimodal-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/your_password_here
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_memory_heap_max__size=2G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - rag-network
    restart: unless-stopped

  # Multimodal RAG Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multimodal-rag-app
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=your_password_here
    volumes:
      - ./data:/app/data
      - ./vectorstore:/app/vectorstore
    depends_on:
      - neo4j
    networks:
      - rag-network
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  rag-network:
    driver: bridge